#!/bin/bash
set -eu

source scripts/common

docker run --rm -t \
  -v ${REPO_ROOT}:${DIR_ON_DOCKER} \
  -v $GOPATH:/go \
  -e "GOPATH=/go" \
  -w ${DIR_ON_DOCKER} \
  tinygo/tinygo:0.22.0 \
  tinygo build -o html/wasm.wasm -target wasm --no-debug ./main.go